baseURL: "https://dany.mestas.dev/" 
title: Dany Mestas
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: papers/
          weight: 1
        #- name: Talks
        #  url: talks/
        #  weight: 2
        #- name: Resume
        #  url: cv_rosa.pdf
        #  weight: 3 
        # - name: Photography
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "I am a PhD Candidate in Distributed Satellite Systems."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    #MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dany Mestas, MSc., MA.
          subtitle: "I am a PhD Candidate in Distributed Satellite Systems."
          imageUrl: "pic/picture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Dany Mestas
          buttons:
            #- name: Publications
            #  url: papers/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
           # - name: Newsletter
           #   url: https://pmichaillat.substack.com
            # - name: Tags
            #   url: tags/
            #- name: Talks
            #  url: talks/
            #- name: Resume
            #  url: cv_rosa.pdf
            #- name: Archive
            #  url: archive/

    socialIcons:
        # - name: CV
        #   url: cv.pdf
        - name: Email
          url: mailto:dany.mestas@ieee.org
        #- name: signal
        #  url: signal:test
        - name: Location
          url: location/
        #- name: Google Scholar
        #  url: .
        - name: ORCID
          url: https://orcid.org/0000-0003-1578-009X
        - name: LinkedIn
          url: https://linkedin.com/in/dany-m/
        - name: GitHub
          url: https://github.com/danypm
        - name: tryhackme
          url: https://tryhackme.com/p/DanyP

    assets:
        #disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Dany Mestas"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
